In [24]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import itertools 
from multiprocessing import Pool
import functools

In [3]:
def getSoupFromURL(url, method='get', data={}):

  if method == 'get':
    res = requests.get(url)
  elif method == 'post':
    res = requests.post(url, data=data)
  else:
    return None

  if res.status_code == 200:
    soup = BeautifulSoup(res.text, 'html.parser')
    return soup
  else:
    return None

In [28]:

def get_distance(city1,city2):
    
    url_distance = 'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=' + city1 + '&destinations='+ city2+'&key=AIzaSyBKp5mwxpY27I0DOWmDn8EfjaUklYZl1KI'
    r = requests.get(url_distance)
    return r.json()['destination_addresses'],r.json()['rows'][0]['elements'][0]['distance']['value']

In [11]:
def get_list_top_cities():
    url_cities = 'https://lespoir.jimdo.com/2015/03/05/classement-des-plus-grandes-villes-de-france-source-insee/'
    soup = getSoupFromURL(url_cities)
    
    tab_cities = []
    for i in range(1,20):
        tab_cities.append(soup.find_all('tr')[i].find_all('td')[1].text.replace('\n            ',''))
    return tab_cities

In [12]:
a = get_list_top_cities()

In [27]:
d = pd.DataFrame(0, index=a, columns=a)
for city in a:
    for citybis in a: 
        d[city].loc[citybis] = get_distance(city,citybis)[1]

In [14]:
d

,Paris,Marseille,Lyon,Toulouse,Nice,Nantes,Strasbourg,Montpellier,Bordeaux,Lille,Rennes,Reims,Le Havre,Saint-Étienne,Toulon,Grenoble,Dijon,Angers,Nîmes
Paris,0,774987,466033,678897,932067,384535,490230,747998,590485,239818,348782,143299,196860,523336,839315,574815,314553,295636,712958
Marseille,776442,0,314191,403677,204591,986092,799554,168944,645721,1002452,1041039,800147,966581,331986,65159,306222,505430,904203,123024
Lyon,464588,313764,0,537748,470845,684551,488664,303015,555450,690597,766578,488293,654727,62114,378093,114318,193575,595652,251736
Toulouse,679215,403226,537330,0,560306,586014,970963,242302,245643,909552,705343,812987,848426,536728,467554,529361,672752,636829,290565
Nice,933491,206569,471240,560726,0,1143141,784276,325993,802770,1159501,1198088,957196,1123630,489035,149102,463271,662479,1061252,280073
Nantes,384569,985758,686269,584967,1142839,0,865271,824835,353412,614906,112925,518341,383837,663852,1050087,795777,639005,91416,873097
Strasbourg,491678,798460,487680,968788,784927,865809,0,787711,968342,525123,830056,351820,699995,546809,862788,573274,331185,776910,736431
Montpellier,747619,170462,304567,242629,327543,825044,789929,0,484673,992827,906889,790523,916830,322362,234791,296598,495805,770053,57802
Bordeaux,584305,645467,557097,244676,802547,346917,968915,484543,0,814642,466246,718077,685713,534680,709795,666605,670704,397733,532806
Lille,228177,999908,690955,897141,1156989,602779,524637,989159,808729,0,571177,204584,317909,748258,1064237,799737,500763,513880,937880
Rennes,354494,1046842,775041,703764,1203922,113313,835196,913572,472210,570950,0,488266,278773,717221,1111170,883823,623560,137600,991895
Reims,144179,798102,489148,812673,955182,518311,350433,787352,724261,206490,482558,0,352360,546451,862430,597930,298957,429412,736073
Le Havre,195878,965513,656559,859129,1122593,384408,698863,928231,691437,316404,278582,351207,0,731880,1029841,765341,505079,328693,903484
Saint-Étienne,552908,332109,62756,535588,489189,664242,548119,321360,535141,751017,712178,548713,722119,0,396438,158058,253995,575342,270080
Toulon,840375,66311,378124,467610,149524,1050025,863486,232877,709653,1066384,1104971,864080,1030514,395919,0,370155,569362,968136,186956
Grenoble,575418,305692,111391,529676,462773,794155,575192,294943,665054,801427,877407,599123,765557,157248,370021,0,304405,705255,243664
Dijon,314940,504705,195751,671675,661785,638071,329865,493956,671228,501754,616930,299450,505079,253054,569033,304533,0,549171,442676
Angers,295975,904879,597675,642452,1061959,90720,776677,771609,410897,526313,125538,429747,328974,575258,969208,707183,550411,0,826460
Nîmes,713616,121628,251365,290728,278708,873144,736727,55996,532772,939626,992472,737321,903755,269160,185956,243396,442604,841377,0

In [25]:
'''
COMMENT FAIRE UN MAP AVEC UNE FINCTION A PLUSIURS PARAMETRES 

c = itertools.combinations(a,2)
p = Pool(8)
h = p.map(get_distance,list(c))
'''

'\nCOMMENT FAIRE UN MAP AVEC UNE FINCTION A PLUSIURS PARAMETRES \n\nc = itertools.combinations(a,2)\np = Pool(8)\nh = p.map(get_distance,list(c))\n'